### ISSUE TITLE
Use custom domain with @analytics/simple-analytics

### ISSUE THREAD

**Issue by xorob0** [simpleanalytics/scripts#11]
Hey guys

I'm trying to setup analytics on a website but it seems like the url of simple analytics is hardcoded in [the library](https://www.npmjs.com/package/@analytics/simple-analytics). I can do a PR myself but I do know where to find the source code for the npm package.

Thanks in advance
Tim

**Comment by adriaanvanrossum** [comment]
Hey Tim! The source code lives here: https://github.com/DavidWells/analytics/tree/master/packages/analytics-plugin-simple-analytics. The code is owned by @DavidWells and he might be able to guide you in the right direction if needed. Please let me know if that doesn't work out, happy to help!

**Comment by xorob0** [comment]
Thanks, I opened a PR there ;)
