### ISSUE TITLE
Sentry recording errors with beacon

### ISSUE THREAD

**Issue by Jivings** [simpleanalytics/scripts#22]
My Sentry is showing errors thrown in the SA script, looks like it's this line:

https://github.com/simpleanalytics/scripts/blob/ed9efd1b5ff62f27e0dc395d57068ac6a0517d14/src/default.js#L484

Here's a link to the Sentry issue:

https://sentry.io/share/issue/20005bc054fb4e48a65b8c01209ae3d2/

<img width="827" alt="image" src="https://user-images.githubusercontent.com/1462828/150667023-70068aac-68fd-42bf-844d-543ae9ceed92.png">

**Comment by Jivings** [comment]
I think it's because you can't use the `navigator` object as a reference without binding it's scope. So you should be invoking it with `call` or `apply`.

```
nav[sendBeaconText].call(
  nav, 
  fullApiUrl + "/append",
  stringify(assign(payload, append))
);

**Comment by adriaanvanrossum** [comment]
Thanks for investigating this! Will update the script when I'm back from my holiday.

**Comment by Jivings** [comment]
Yes that should be fine.

**Comment by adriaanvanrossum** [comment]
Fixed in https://github.com/simpleanalytics/scripts/pull/29
