### ISSUE TITLE
Scrolled bug

### ISSUE THREAD

**Issue by maximeg** [simpleanalytics/scripts#7]
Hi there,

I Was looking at your code and saw that:

```javascript
scrolled = window.setTimeout(position, 500);
```

https://github.com/simpleanalytics/scripts/blob/7a93d220f9572155953b54385862874cc448520f/src/default.js#L337

`setTimeout` returns a TimeoutID, that we can pass to `clearTimeout`to cancel the future call. So it won't do what you think.

You may want to do:

```javascript
window.setTimeout(function () {
  scrolled = position()
}, 500);
```

Anyway, great product!

**Comment by adriaanvanrossum** [comment]
Thanks!! Will fix this. Currently working on the script so the timing is perfect Maxime.

**Comment by adriaanvanrossum** [comment]
This is now fixed in https://github.com/simpleanalytics/scripts/pull/5!
