### ISSUE TITLE
Event constructor not supported in Internet Explorer 11 and below

### ISSUE THREAD

**Issue by jsutcliffe** [simpleanalytics/scripts#8]
Hello,

The constructor `new Event()` is not supported in Internet Explorer, and this is causing scripts to break when they use `history.pushState()`. It looks like you are checking that `Event` is defined before trying to use the constructor, but `Event` _is_ defined in IE, just not as a function.

There are a couple of possible solutions that come to mind: polyfilling or substituting the constructor somehow, or checking not just that `Event` is defined, but that it is defined as a function.

Thanks,

Jonathan Sutcliffe

**Comment by adriaanvanrossum** [comment]
Hi Jonathan, thanks for showing us! We fixed this already in https://github.com/simpleanalytics/scripts/pull/5 but we will push this to production only after we are done with testing. ETA is around next week. Thanks again for explaining this issue!

**Comment by adriaanvanrossum** [comment]
This is now fixed in https://github.com/simpleanalytics/scripts/pull/5!
